project_id = "zxgkspeehamsrfhynbzr"

[functions.emitir-nfse]
verify_jwt = true

[functions.google-oauth]
verify_jwt = false

[functions.google-oauth-config]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.criar-agendamento]
verify_jwt = false

[functions.certificate-upload]
verify_jwt = false